### ISSUE TITLE
Azure deployment

### ISSUE THREAD

**Issue by cr41g1w** [jerriep/airport-explorer-source#2]
As an extra challenge I deployed the finished application to Azure.  The map and clusters display properly, but I cannot get any item detail.  I suspect it is an issue with the MaxMind.GeoIP2 package but I am not experienced enough with Azure to diagnose and debug the issue properly.

Have you tried deploying the finished application to Azure and did it run successfully?

**Comment by cr41g1w** [comment]
Well it's not the GeoIP.  I get a 404 response in the browser when invoking the OnGetAirportDetail handler:  I can't remote debug from here and didn't see any error logs generated yet.  Will keep looking.  Same code works fine locally.

**Comment by cr41g1w** [comment]
It's the User Secret that stores the API Key for the Google Places API.  It seems Azure is not able to access the secret:

2018-01-29 11:17:15.278 +00:00 [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred: Key is required
System.ArgumentException: Key is required
   at GoogleApi.Entities.Places.BasePlacesRequest.GetQueryStringParameters()
   at GoogleApi.Entities.Places.Search.BasePlacesSearchRequest.GetQueryStringParameters()
   at GoogleApi.Entities.Places.Search.NearBy.Request.PlacesNearBySearchRequest.GetQueryStringParameters()
   at GoogleApi.Entities.BaseRequest.GetUri()
   at GoogleApi.HttpEngine`2.QueryAsync(TRequest request, TimeSpan timeout, CancellationToken cancellationToken)
   at GoogleApi.HttpEngine`2.QueryAsync(TRequest request, CancellationToken cancellationToken)
   at GoogleApi.HttpEngine`2.QueryAsync(TRequest request)
   at AirportExplorer.Pages.IndexModel.<OnGetAirportDetail>d__22.MoveNext() in C:\Users\cr41g1w\Documents\Visual Studio 2017\Projects\AirportExplorer\AirportExplorer\Pages\Index.cshtml.cs:line 105

**Comment by cr41g1w** [comment]
Confirmed.  Moving my Google API key from secrets.json to appsettings.json fixed the problem.  I'll close this for now but it's maybe worth putting a note in the book saying that the 'User Secrets' approach isn't straightforward if deploying to Azure.

**Comment by supernarwen** [comment]
U need to setup ur secrets.json file in azure storage! Have a look at this! https://blogs.msdn.microsoft.com/dotnet/2016/10/03/storing-and-using-secrets-in-azure/

**Comment by cr41g1w** [comment]
@supernarwen seems a good writeup, though it appears it requires code changes to the project to enable use of secrets stored in Azure.  Not sure how to square that with local development.

**Comment by jerriep** [comment]
Yeah, user secrets only work on a local computer. For Azure you will need to store the configuration settings in the Azure Application's environment settings.

I'll look into maybe adding a chapter for deploying to Azure in the future
